caja/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    #path('registrar_cita/', CrearCita.as_view(), name="registrar_cita"),
    path('listar_pagos_hoy/', ListarPagosHoy.as_view(), name="listar_pagos_hoy"),
    path('abrir_caja/', abrir_caja, name="abrir_caja"),
    path('cerrar_caja/<int:id_caja>', cerrar_caja, name="cerrar_caja"),
    path('listar_cajas/', ListarCajas.as_view(), name="listar_cajas"),
    path('detalle_caja/<int:id_caja>/', ListarPagosSelected.as_view(), name="detalle_caja"),
    path('registrar_compra_caja/', registrar_compra_caja, name="registrar_compra_caja"),
    path('registrar_pago_caja/', crearPago_caja, name="registrar_pago_caja"),
    path('registrar_gasto_caja/', CrearGastoCaja.as_view(), name="registrar_gasto"),
    path('ajax/registrar_pago_caja/', registrarPago_caja, name="ajax_registrar_pago"),
    path('agregar_caja/', agregar_caja, name="agregar_caja"),
]

guarderia/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('programar_guarderia/<int:id_mascota>/', CrearGuarderia.as_view(), name="programar_guarderia"),
    path('editar_guarderia/<int:pk>/', EditarGuarderia.as_view(), name="editar_guarderia"),
    path('eliminar_guarderia/', eliminar_guarderia, name="eliminar_guarderia"),
    path('registrar_cita_guarderia/<str:fecha>/', registrar_cita_guarderia, name="registrar_cita_guarderia"),
    path('editar_guarderia_agenda/<int:pk>/', EditarGuarderiaAgenda.as_view(), name="editar_guarderia_agenda"),
    path('pdf_guarderia/<int:id_mascota>/<str:fecha_inicio>/<str:fecha_fin>/<int:id_guarderia>/', PdfGuarderia.as_view(), name="pdf_guarderia"),
    path('detalle_impresion_guarderia/<int:id_mascota>/<str:fecha_inicio>/<str:fecha_fin>/<int:id_guarderia>/', DetalleImpresionGuarderia.as_view(), name="detalle_impresion_guarderia"),
    path('datos_guarderia/<int:id_guarderia>/', DatoGuarderia.as_view(), name="datos_guarderia"),
    path('registrar_representante_ingreso/<int:id_guarderia>/', RegistrarRepresentanteIngreso.as_view(), name="registrar_representante_ingreso"),
    path('registrar_representante_egreso/<int:id_datosg>/', RegistrarRepresentanteEgreso, name="registrar_representante_egreso"),
    path('act_representante_retiro/', actRepresentanteRetiro, name="act_representante_retiro")
]

guarderia/models.py
from django.db import models
from mascotas.models import Mascota
from django.core.validators import RegexValidator
from django.contrib.auth.models import Group
import sys
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
import re
from usuarios.models import Usuario

ESTADOS_GUARDERIA = (('Activa','Activa'),('Pagada','Pagada'))
numeric = RegexValidator(r'^[0-9]*$', 'Solamente valores númericos')

def get_upload_to_ingreso(instance, filename):
    return 'upload/%s/%s' % (instance.numero_documento_identificacion_ingreso, filename)

def get_upload_to_retiro(instance, filename):
    return 'upload/%s/%s' % (instance.numero_documento_identificacion_retiro, filename)


def validate_file_extension(value):
    import os
    from django.core.exceptions import ValidationError
    ext = os.path.splitext(value.name)[1]  # [0] returns path+filename
    valid_extensions = ['.jpg', '.JPG', '.jpeg', '.JPEG', '.png', '.PNG']
    if not ext.lower() in valid_extensions:
        raise ValidationError(u'Unsupported file extension.')


class Guarderia(models.Model):
    mascota = models.ForeignKey(Mascota, on_delete=models.CASCADE)
    fecha_inicio = models.DateTimeField()
    fecha_fin = models.DateTimeField()
    observaciones = models.CharField(max_length=2000, verbose_name='Observaciones')
    estado = models.CharField(max_length=20, verbose_name="Estado", choices=ESTADOS_GUARDERIA, default='Activa')

    def __str__(self):
        return self.mascota.nombre + " - " + str(self.fecha_inicio.strftime('%b. %d, %Y, %H:%M %p'))

class DatosGuarderia(models.Model):
    guarderia = models.ForeignKey(Guarderia, on_delete=models.CASCADE)
    descripcion = models.CharField(max_length=2000, verbose_name='Descripción')
    representante_ingreso = models.CharField(max_length=100, verbose_name="Representante Ingreso")
    numero_documento_identificacion_ingreso = models.CharField(max_length=20,verbose_name="Número de Documento Ingreso",validators=[numeric])
    foto_ingreso = models.ImageField(upload_to=get_upload_to_ingreso, validators=[validate_file_extension], null=True, blank=True)
    representante_retiro = models.CharField(max_length=100, verbose_name="Representante Retiro")
    numero_documento_identificacion_retiro = models.CharField(max_length=20,verbose_name="Número de Documento Retiro",validators=[numeric])
    foto_retiro = models.ImageField(upload_to=get_upload_to_retiro, validators=[validate_file_extension], null=True, blank=True)
    descripcion_salida = models.CharField(max_length=2000, verbose_name='Descripción de Salida', null=True, blank=True)
    responsable = models.ForeignKey(Usuario, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return '%s (%s)' % (self.descripcion, self.guarderia)

guarderia/views.py
from django.views.generic import *
from .models import *
from .forms import *
from django.shortcuts import get_object_or_404,render,redirect
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from mascotas.models import Mascota
from django.http import JsonResponse
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.urls import reverse_lazy
from veteriariaTenant.models import Veterinaria
from usuarios.models import Usuario
from django.contrib.auth.models import User


class CrearGuarderia(SuccessMessageMixin, CreateView):
    model = Guarderia
    form_class = CrearGuarderiaForm
    template_name = "registrar_guarderia.html"
    success_message = "¡Guardería creada con exito!"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(CrearGuarderia, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        mi_mascota =  get_object_or_404(Mascota, pk=self.kwargs['id_mascota'])
        return '/mascotas/detalle_mascota/' + str(mi_mascota.id)

    def form_valid(self,form):
        guarderia = form.instance
        guarderia.mascota = get_object_or_404(Mascota, pk=self.kwargs['id_mascota'])

        self.object = form.save()
        return super(CrearGuarderia, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CrearGuarderia, self).get_context_data(**kwargs)
        context['modificar'] = False
        context['mascotas'] = True
        context['mascota'] = get_object_or_404(Mascota, pk=self.kwargs['id_mascota'])
        return context


class EditarGuarderia(SuccessMessageMixin, UpdateView):
    model = Guarderia
    form_class = CrearGuarderiaForm
    template_name = "registrar_guarderia.html"
    success_message = "¡Guardería editada con exito!"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(EditarGuarderia, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        mi_guarderia = get_object_or_404(Guarderia, pk=self.kwargs['pk'])
        return '/mascotas/detalle_mascota/' + str(mi_guarderia.mascota.id)

    def get_context_data(self, **kwargs):
        context = super(EditarGuarderia, self).get_context_data(**kwargs)
        context['modificar'] = True
        context['mascotas'] = True
        mi_guarderia = get_object_or_404(Guarderia, pk=self.kwargs['pk'])
        context['mascota'] = mi_guarderia.mascota
        return context


class EditarGuarderiaAgenda(SuccessMessageMixin, UpdateView):
    model = Guarderia
    form_class = CrearGuarderiaForm
    template_name = "registrar_guarderia.html"
    success_url = reverse_lazy('listar_citas')
    success_message = "¡Guardería editada con exito!"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(EditarGuarderiaAgenda, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(EditarGuarderiaAgenda, self).get_context_data(**kwargs)
        context['modificar'] = True
        context['mascotas'] = True
        mi_guarderia = get_object_or_404(Guarderia, pk=self.kwargs['pk'])
        context['mascota'] = mi_guarderia.mascota
        return context


def eliminar_guarderia(request):
    id_guarderia = request.GET.get('id', '')
    mi_guarderia = get_object_or_404(Guarderia, pk=id_guarderia)
    id_mascota = mi_guarderia.mascota.id
    if mi_guarderia.estado == 'Activa':
        mi_guarderia.delete()
    data = {
        'eliminacion': True,
        'id_mascota': id_mascota
    }
    return JsonResponse(data)

def registrar_cita_guarderia(request,fecha):
    if request.method == "GET":
        return render(request,'registrar_cita_guarderia_agenda.html',{'citas': True,'fecha':fecha,'form':CrearGuarderiaFormAgenda()})
    if request.method == "POST":
        print("inside POST")
        form_cita =CrearGuarderiaFormAgenda(request.POST)
        form_cita.save()

        return redirect('listar_citas')

class RegistrarRepresentanteIngreso(SuccessMessageMixin, CreateView):
    model = DatosGuarderia
    form_class = CrearIngresoForm
    template_name = 'registrar_representante_ingreso.html'
    success_message = "Ingreso de Guarderia creado con exito"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(RegistrarRepresentanteIngreso, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return '/citas/listar_citas/'

    def form_valid(self, form):
        datos = form.instance
        datos.guarderia = get_object_or_404(Guarderia, pk=self.kwargs['id_guarderia'])
        datos.responsable = get_object_or_404(Usuario, id=self.request.user.id)
        self.object = form.save()
        return super(RegistrarRepresentanteIngreso, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(RegistrarRepresentanteIngreso, self).get_context_data(**kwargs)
        guarderia = get_object_or_404(Guarderia, pk=self.kwargs['id_guarderia'])

        context['modificar'] = False
        context['guarderia'] = guarderia

        return context

class PdfGuarderia(TemplateView):
    template_name = 'pdf_guarderia.html'

    def get_context_data(self, **kwargs):
        context = super(PdfGuarderia, self).get_context_data(**kwargs)
        mascota = get_object_or_404(Mascota, pk=self.kwargs['id_mascota'])
        fecha_inicio = self.kwargs['fecha_inicio']
        fecha_fin = self.kwargs['fecha_fin']
        id_guarderia = self.kwargs['id_guarderia']

        hay_veterinaria = Veterinaria.objects.filter(pk='1')

        if hay_veterinaria:
            context['mi_veterinaria'] = Veterinaria.objects.get(pk='1')

        guarderias = Guarderia.objects.filter(mascota_id=self.kwargs['id_mascota']).filter(fecha_inicio=fecha_inicio).filter(fecha_fin=fecha_fin)
        datos_guarderias = DatosGuarderia.objects.filter(guarderia_id=id_guarderia)

        for guarderia in guarderias:
            context['guarderia'] = guarderia

        for dato in datos_guarderias:
            context['dato'] = dato

        context['fecha_hoy'] = datetime.now().date()
        context['mi_mascota'] = mascota

        return context

class DetalleImpresionGuarderia(TemplateView):
    template_name = 'detalle_impresion_guarderia.html'

    def get_context_data(self, **kwargs):
        context = super(DetalleImpresionGuarderia, self).get_context_data(**kwargs)
        mascota = get_object_or_404(Mascota, pk=self.kwargs['id_mascota'])
        fecha_inicio = self.kwargs['fecha_inicio']
        fecha_fin = self.kwargs['fecha_fin']
        id_guarderia = self.kwargs['id_guarderia']

        hay_veterinaria = Veterinaria.objects.filter(pk='1')

        if hay_veterinaria:
            context['mi_veterinaria'] = Veterinaria.objects.get(pk='1')

        guarderias = Guarderia.objects.filter(mascota_id=self.kwargs['id_mascota']).filter(fecha_inicio=fecha_inicio).filter(fecha_fin=fecha_fin)
        datos_guarderias = DatosGuarderia.objects.filter(guarderia_id=id_guarderia)

        for guarderia in guarderias:
            context['guarderia'] = guarderia

        for dato in datos_guarderias:
            context['dato'] = dato


        context['fecha_hoy'] = datetime.now().date()
        context['mi_mascota'] = mascota

        return context

class DatoGuarderia(SuccessMessageMixin, CreateView):
    model = DatosGuarderia
    form_class = CrearDatosGuarderia
    template_name = "datos_guarderia.html"
    success_message = "¡Datos Guarderia actualizada con exito!"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(DatoGuarderia, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return '/mascotas/listar_mascotas/'

    def form_valid(self,form):
        guarderia = form.instance
        guarderia.guarderia = get_object_or_404(Guarderia, pk=self.kwargs['id_guarderia'])
        guarderia.responsable = get_object_or_404(Usuario, id=self.request.user.id)
        self.object = form.save()
        return super(DatoGuarderia, self).form_valid(form)

    def get_context_data(self, **kwargs):
        model = DatosGuarderia
        context = super(DatoGuarderia, self).get_context_data(**kwargs)
        guarderia_val = DatosGuarderia.objects.filter(guarderia_id=self.kwargs['id_guarderia'])
        
        if guarderia_val:
            context['agregar'] = False
            context['datos'] = guarderia_val
            
        else:
            context['agregar'] = True
        
        context['guarderia'] = get_object_or_404(Guarderia, pk=self.kwargs['id_guarderia'])

        return context

def RegistrarRepresentanteEgreso(request, id_datosg):

    return render(request, 'registrar_representante_egreso.html', {
        'id_datosg': id_datosg,
    })

def actRepresentanteRetiro(request):
    id_datosg = request.GET.get('id_datosg', '')
    representante = request.GET.get('representante', '')
    identificacion = request.GET.get('identificacion', '')
    descripcion_salida = request.GET.get('descripcion_salida', '')
    foto = request.GET.get('foto', '')

    datos = DatosGuarderia.objects.filter(id=id_datosg)
    #datos = datos[0]
    for dato in datos:
        dato.representante_retiro = representante
        dato.numero_documento_identificacion_retiro = identificacion
        dato.descripcion_salida = descripcion_salida
        dato.foto_retiro = foto
        dato.save()

    #term_cond = TerminosCondiciones.objects.create(fecha_registro=fecha_actual,revisado=True,cliente_id=id_user,veterinaria=datos[0],observaciones=observaciones)
    #term_cond.save()

    data = {
        'actualizado': True
    }
    return JsonResponse(data)

guarderia/templates/datos_guarderia.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block title %}
    Registrar Datos de la Guarderia
{% endblock title %}

{% block extrahead %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/select2.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/css/bootstrap-select.min.css" />
{% endblock%}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <h4 class="page-title">
                {% if agregar %}
                    Agregar Datos de la Guarderia
                {% else %}
                    Ver Informacion
                {% endif %}
            </h4>
            <ol class="breadcrumb">
                <li><a href="/usuario/index/">Inicio</a></li>
                <li class="active"><a>{% if agregar %}Agregar Datos de la Guarderia{% else %}Ver Informacion{% endif %}</a></li>
            </ol> 
        </div>
    </div>
    <form class="form-horizontal" method="POST" action="" autocomplete="off" enctype="multipart/form-data">{% csrf_token %}
        <div class="card-box" style="padding-left: 15px;">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group" style="margin: 15px;">
                        <div class="form-group">
                            <label class="col-lg-3 control-label">Observaciones</label>
                            <div class="col-lg-9">
                                <input class="form-control" type="text" disabled value="{{guarderia.observaciones}}">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group" style="margin: 15px;">
                        <div class="form-group">
                            <label class="col-lg-3 control-label">Mascota</label>
                            <div class="col-lg-9">
                                <input class="form-control" type="text" disabled value="{{ guarderia.mascota.nombre }}">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group" style="margin: 15px;">
                        <div class="form-group">
                            <label class="col-lg-3 control-label">Guarderia</label>
                            <div class="col-lg-9">
                                <input class="form-control" type="text" disabled value="{{ guarderia }}">
                            </div>
                        </div>
                    </div>
                </div>
                {% if agregar %}
                    {% for field in form %}
                        <div class="col-md-6">
                            <div class="form-group" style="margin: 15px;">
                                {% bootstrap_field field label_class="control-label col-lg-3" field_class="col-lg-9" %}
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    {% for dato in datos %}
                        <div class="col-md-6">
                            <div class="form-group" style="margin: 15px;">
                                <div class="form-group">
                                    <label class="col-lg-3 control-label">Guarderia</label>
                                    <div class="col-lg-9">
                                        <input class="form-control" type="text" disabled value="{{ dato.guarderia }}">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group" style="margin: 15px;">
                                <div class="form-group">
                                    <label class="col-lg-3 control-label">Descripcion</label>
                                    <div class="col-lg-9">
                                        <input class="form-control" type="text" disabled value="{{ dato.descripcion }}">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group" style="margin: 15px;">
                                <div class="form-group">
                                    <label class="col-lg-6 control-label">Representante Ingreso</label>
                                    <div class="col-lg-6">
                                        <input class="form-control" type="text" disabled value="{{ dato.representante_ingreso }}">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group" style="margin: 15px;">
                                <div class="form-group">
                                    <label class="col-lg-8 control-label">Numero Documento de Identificacion Ingreso</label>
                                    <div class="col-lg-4">
                                        <input class="form-control" type="text" disabled value="{{ dato.numero_documento_identificacion_ingreso }}">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-9">
                            <div class="form-group" style="margin: 15px;">
                                <div class="form-group">
                                    <label class="col-lg-6 control-label">Foto de Ingreso</label>
                                    <div class="col-lg-6">
                                        {% if dato.foto_ingreso %}
                                            <img width="350" height="250" src="/media/{{ dato.foto_ingreso }}">
                                        {% else %}
                                            <p> No Adjuntada </p>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% if dato.representante_retiro %}
                            <div class="col-md-6">
                                <div class="form-group" style="margin: 15px;">
                                    <div class="form-group">
                                        <label class="col-lg-6 control-label">Descripción Retiro</label>
                                        <div class="col-lg-6">
                                            <input class="form-control" type="text" disabled value="{{ dato.descripcion_salida }}">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group" style="margin: 15px;">
                                    <div class="form-group">
                                        <label class="col-lg-6 control-label">Representante Retiro</label>
                                        <div class="col-lg-6">
                                            <input class="form-control" type="text" disabled value="{{ dato.representante_retiro }}">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group" style="margin: 15px;">
                                    <div class="form-group">
                                        <label class="col-lg-8 control-label">Numero Documento de Identificacion Retiro</label>
                                        <div class="col-lg-4">
                                            <input class="form-control" type="text" disabled value="{{ dato.numero_documento_identificacion_retiro }}">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group" style="margin: 15px;">
                                    <div class="form-group">
                                        <label class="col-lg-8 control-label">Responsable</label>
                                        <div class="col-lg-4">
                                            <p>{{ dato.responsable }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-9">
                                <div class="form-group" style="margin: 15px;">
                                    <div class="form-group">
                                        <label class="col-lg-6 control-label">Foto de Retiro</label>
                                        <div class="col-lg-6">
                                            {% if dato.foto_retiro %}
                                                <img width="350" height="250" src="/media/{{ dato.foto_retiro }}">
                                            {% else %}
                                                <p> No Adjuntada </p>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            <a href="{% url 'registrar_representante_egreso' dato.id %}" class="btn add-btn btn-custom pull-right m-b-30 m-r-20" style="margin-bottom:0px!important;background-color: #de6f4e;border-color: #fff;">Ingresar Representante Retiro</a>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="text-center submit-btns">
            {% if agregar %}
                {% bootstrap_button "Agregar" button_type="submit" button_class="btn btn-primary m-r-20" %}
                <a href="{% url 'detalle_mascota' guarderia.mascota.id %}" class="btn btn-danger">Cancelar</a>
            {% else %}
                <a href="{% url 'detalle_mascota' guarderia.mascota.id %}" class="btn btn-primary">Regresar</a>
            {% endif %}
        </div>
    </form>
{% endblock content %}

{% block plugins %}
    <script type="text/javascript" src="{% static 'js/select2.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/moment.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/js/bootstrap-select.min.js"></script>
{% endblock %}

guarderia/templates/registrar_cita_guarderia_agenda.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block title %}
Guarderia
{% endblock title %}

{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{% static 'css/select2.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/css/bootstrap-select.min.css"/>
    <style>
        .select2-selection__rendered {
            line-height: 31px !important;
        }
        .select2-container .select2-selection--single {
            height: 35px !important;
        }
        .select2-selection__arrow {
            height: 34px !important;
        }
    </style>
{% endblock%}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title">
            {% if modificar %}
                Modificar guardería
            {% else %}
                Programar guardería
            {% endif %}
        </h4>
        <ol class="breadcrumb">
            <li><a href="/usuario/index/">Inicio</a></li>
            <li><a href="/citas/listar_citas/">Agenda</a></li>
            <li class="active"><a>{% if modificar %}Modificar guardería{% else %}Programar guardería{% endif %}</a></li>
        </ol> 
    </div>
</div>
<form class="form-horizontal" method="POST" action="" autocomplete="off">{% csrf_token %}
    <div class="card-box">
        <div class="row">
            
            <div class="col-md-6">
                <div class="form-group" style="margin: 15px;">
                    {% bootstrap_field form.mascota label_class="control-label col-lg-3" field_class="col-lg-9" %}
                </div>
                <div class="form-group" id="firstdate" style="margin: 15px;">
                    {% bootstrap_field form.fecha_inicio label_class="control-label col-lg-3" field_class="col-lg-9" %}
                </div>
                <div class="form-group" style="margin: 15px;">
                    {% bootstrap_field form.fecha_fin label_class="control-label col-lg-3" field_class="col-lg-9" %}
                </div>
                
            </div>
            <div class="col-md-6">
                <div class="form-group" style="margin: 15px;">
                    {% bootstrap_field form.observaciones label_class="control-label col-lg-3" field_class="col-lg-9" %}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                
            </div>
            
        </div>
        <div class="row">
            <div class="col-md-6">
                
            </div>
        </div>
    </div>
    <div class="text-center submit-btns">
        {% if modificar %}
        {% bootstrap_button "Guardar cambios" button_type="submit" button_class="btn btn-primary m-r-20" %}
        {% else %}
        {% bootstrap_button "Agregar" button_type="submit" button_class="btn btn-primary m-r-20 boton_agregar" %}
        {% endif %}
        <a href="#" onclick="window.history.back();" class="btn btn-danger">Cancelar</a>
    </div>
</form>
{% endblock content %}

{% block plugins %}
<script type="text/javascript" src="{% static 'js/select2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/moment.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/js/bootstrap-select.min.js"></script>

<script type="text/javascript">
    $(function () {
        $('#id_mascota').select2();

        $('.datetime-input').datetimepicker({
            format:'DD/MM/YYYY HH:mm',
            date: new Date("{{ fecha }}")
        });
        $('#firstdate').datetimepicker({
            format:'DD/MM/YYYY HH:mm',
            date: new Date("{{ fecha }}")
        });

        $('.boton_agregar').click(
            function () {
                if($('#id_mascota').val() == '' && $('#id_fecha_inico').val() != '' && $('#id_fecha_fin').val() != '' ){
                    swal({
                        icon: 'error',
                        title: 'Debe seleccionar una mascota',
                        button: 'Ok'
                    });
                    setTimeout(function(){
                        $("#pageLoader").hide();
                    }, 500);
                }
            }
        );
        
    });
</script>
{% endblock %}