caja/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    #path('registrar_cita/', CrearCita.as_view(), name="registrar_cita"),
    path('listar_pagos_hoy/', ListarPagosHoy.as_view(), name="listar_pagos_hoy"),
    path('abrir_caja/', abrir_caja, name="abrir_caja"),
    path('cerrar_caja/<int:id_caja>', cerrar_caja, name="cerrar_caja"),
    path('listar_cajas/', ListarCajas.as_view(), name="listar_cajas"),
    path('detalle_caja/<int:id_caja>/', ListarPagosSelected.as_view(), name="detalle_caja"),
    path('registrar_compra_caja/', registrar_compra_caja, name="registrar_compra_caja"),
    path('registrar_pago_caja/', crearPago_caja, name="registrar_pago_caja"),
    path('registrar_gasto_caja/', CrearGastoCaja.as_view(), name="registrar_gasto"),
    path('ajax/registrar_pago_caja/', registrarPago_caja, name="ajax_registrar_pago"),
    path('agregar_caja/', agregar_caja, name="agregar_caja"),
]

citas/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    #path('registrar_cita/', CrearCita.as_view(), name="registrar_cita"),
    path('listar_citas/', ListarCitas.as_view(), name="listar_citas"),
    path('editar_cita/<int:pk>/', EditarCita.as_view(), name="editar_cita"),
    path('registrar_historia/<int:id_cita>/', CrearHistoriaClinica.as_view(), name="registrar_historia_clinica"),
    path('listar_historias/<int:id_mascota>/', ListarHistoriasClinicas.as_view(), name="listar_historias_clinicas"),
    path('registrar_cita_mascota/<int:id_mascota>/', CrearCitaMascota.as_view(), name="registrar_cita_mascota"),
    path('agregar_otra_historia/<int:id_historia>/', AgregarOtraHistoria.as_view(), name="agregar_otra_historia"),
    path('editar_historia/<int:pk>/', EditarHistoria.as_view(), name="editar_historia"),
    path('eliminar_documento/<int:pk>/', EliminarDocumento, name="eliminar_documento"),
    path('agregar_documento_historia/<int:id_historia>/', AgregarDocumentoHistoria.as_view(), name="agregar_documento_historia"),
    path('detalle_impresion_historia/<int:id_mascota>/', DetalleImpresionHistoria.as_view(), name="detalle_impresion_historia"),
    path('detalle_historia_clinica/<int:pk>/', DetalleHistoriaClinica.as_view(), name="detalle_historia_clinica"),
    path('eliminar_cita/', eliminar_cita, name="eliminar_cita"),
    path('registrar_historia_cita/<int:id_cita>/', registrarHistoria, name="registrar_historia_cita"),
    path('ajax_crear_documento/', ajax_crear_documento, name="ajax_crear_documento"),
    path('eliminar_documento_historia/', eliminar_documento_historia, name="eliminar_documento_historia"),
    path('ajax/documentos_historia/', documentos_historia, name="documentos_historia"),
    path('opciones_tratamiento/', enviar_opciones_tratamiento , name="opciones_tratamiento"),
    path('mostrar_citas/', mostrar_citas, name="mostrar_citas"),
    path('registrar_citas/<str:fecha>/', registrar_citas, name="registrar_citas"),
    path('actualizar_areas_consulta/',actualizar_areas_consulta , name="actualizar_areas_consulta"),
    path('remover_area_consulta/',remover_area_consulta, name="remover_area_consulta"),
    path('actualizar_medicamentos/',actualizar_medicamentos, name="actualizar_medicamentos"),
    path('eliminar_medicamentos/',eliminar_medicamentos, name="eliminar_medicamentos"),
    path('actualizar_hospitalizacion/<int:pk>/',actualizar_hospitalizacion.as_view(), name="actualizar_hospitalizacion"),
    path('terminar_hospitalizacion/', terminar_hospitalizacion, name="terminar_hospitalizacion"),
    path('aplicar_medicamentos_hospitalizacion/', aplicar_medicamentos_hospitalizacion, name="aplicar_medicamentos_hospitalizacion"),
    path('crear_nueva_hospitalizacion/<int:id_hospitalizacion_anterior>/', crear_nueva_hospitalizacion, name="crear_nueva_hospitalizacion"),
    path('ajax_nueva_hospitalizacion/', ajax_nueva_hospitalizacion, name="ajax_nueva_hospitalizacion"),
    path('detalle_cita_agenda/<str:tipo_atencion>/<int:id_atencion>/', DetalleCitaAgenda, name='detalle_cita_agenda'),
    path('editar_cita_agenda/<int:pk>/', EditarCitaAgenda.as_view(), name="editar_cita_agenda"),
    path('agregar_insumos_historia/',agregar_insumos_historia, name="agregar_insumos_historia"),
    path('agregar_hospitalizacion_historia/',agregar_hospitalizacion_historia, name="agregar_hospitalizacion_historia"),
    path('agregar_cirugia_historia/',agregar_cirugia_historia, name="agregar_cirugia_historia"),
    path('pdf_historia/<int:id_mascota>/', PdfHistoria.as_view(), name="pdf_historia"),
    path('aplicar_insumos_hospitalizacion/', aplicar_insumos_hospitalizacion, name="aplicar_insumos_hospitalizacion"),
    path('agregar_seguimiento_historia/', agregar_seguimiento_historia, name="agregar_seguimiento_historia"),
    path('editar_seguimiento_historia/', editar_seguimiento_historia, name="editar_seguimiento_historia"),
]

citas/models.py
from django.db import models
from mascotas.models import Mascota
from usuarios.models import Veterinario, Usuario
from tratamientos.models import Tratamiento
import datetime
from django.db import connection
import sys
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile


def get_upload_to(instance, filename):
    return 'upload/%s/%s' % (instance.mascota.cliente.numero_documento, filename)

def get_upload_to_documento(instance, filename):
    tenant_name = connection.tenant.schema_name
    return 'upload/%s/documentos_historias/%s' % (tenant_name, filename)

def validate_file_extension(value):
    import os
    from django.core.exceptions import ValidationError
    ext = os.path.splitext(value.name)[1]  # [0] returns path+filename
    valid_extensions = ['.zip','.tar','.pdf','.PDF','.jpg', '.JPG', '.jpeg', '.JPEG', '.png', '.PNG']
    if not ext.lower() in valid_extensions:
        raise ValidationError(u'Extension del archivo no valida')


ESTADOS_CITA = (('Activa','Activa'),('Cancelada','Cancelada'),('Atendida','Atendida'))


class Cita(models.Model):
    mascota = models.ForeignKey(Mascota, on_delete=models.CASCADE)
    veterinario = models.ForeignKey(Veterinario, on_delete=models.CASCADE, limit_choices_to={'is_active': True})
    fecha = models.DateTimeField()
    proxima_cita = models.DateTimeField(null=True, blank=True)
    motivo_cita = models.CharField(max_length=2000, verbose_name='Motivo cita')
    motivo_proxima_cita = models.CharField(max_length=2000, verbose_name='Motivo próxima cita', null=True, blank=True)
    estado = models.CharField(max_length=10, verbose_name="Estado", choices=ESTADOS_CITA, default='Activa')
    email_sent = models.BooleanField(default = False)

    def __str__(self):
        return self.mascota.nombre + " - " + str(self.fecha.strftime('%b. %d, %Y, %H:%M %p'))


MOTIVOS_HISTORIA = (('Estado inicial','Estado inicial'),('Historia adicional','Historia adicional'))

ESTADOS_HISTORIA = (('Activa','Activa'),('Pagada','Pagada'))


class HistoriaClinica(models.Model):
    mascota = models.ForeignKey(Mascota, on_delete=models.CASCADE)
    cita = models.ForeignKey(Cita, on_delete=models.CASCADE, blank=True, null=True)
    fecha = models.DateTimeField()
    creada_por = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    motivo = models.CharField(max_length=1000, verbose_name='Motivo', default='Estado inicial')
    descripcion = models.CharField(max_length=10000, verbose_name='Descripción')
    archivo_zip = models.FileField(upload_to=get_upload_to, validators=[validate_file_extension], null=True, blank=True)
    tratamiento = models.ForeignKey(Tratamiento, on_delete=models.CASCADE, blank=True, null=True)
    estado = models.CharField(max_length=10, verbose_name="Estado", choices=ESTADOS_HISTORIA, default='Activa')
    costo = models.DecimalField(max_digits=50, decimal_places=0, verbose_name='Costo', default=0)
    senales = models.CharField(max_length=2000, verbose_name='Señales', null=True, blank=True)
    estado_reproductivo = models.CharField(max_length=2000, verbose_name='Estado reproductivo', null=True, blank=True)
    numero_partos = models.CharField(max_length=2000, verbose_name='Número de partos', null=True, blank=True)
    tipo_alimento = models.CharField(max_length=2000, verbose_name='Tipo de alimento', null=True, blank=True)
    racion_alimento = models.CharField(max_length=2000, verbose_name='Ración', null=True, blank=True)
    vacunacion = models.CharField(max_length=2000, verbose_name='Vacunación', null=True, blank=True)
    desparasitacion = models.CharField(max_length=2000, verbose_name='Desparasitación', null=True, blank=True)
    heces = models.CharField(max_length=2000, verbose_name='Heces', null=True, blank=True)
    orina = models.CharField(max_length=2000, verbose_name='Orina', null=True, blank=True)
    frecuencia_cardiaca = models.CharField(max_length=2000, verbose_name='F.C.', null=True, blank=True)
    frecuencia_respiratoria = models.CharField(max_length=2000, verbose_name='F.R.', null=True, blank=True)
    temperatura = models.CharField(max_length=2000, verbose_name='T°', null=True, blank=True)
    tiempo_llenado_capilar = models.CharField(max_length=2000, verbose_name='Tllc', null=True, blank=True)
    pulso = models.CharField(max_length=2000, verbose_name='Pulso', null=True, blank=True)
    peso = models.CharField(max_length=2000, verbose_name='Peso', null=True, blank=True)
    actitud = models.CharField(max_length=2000, verbose_name='Actitud', null=True, blank=True)
    estado_corporal = models.CharField(max_length=2000, verbose_name='C/C', null=True, blank=True)
    comentarios_examen_clinico = models.CharField(max_length=4000, verbose_name='Comentarios', null=True, blank=True)
    listado_problemas = models.CharField(max_length=4000, verbose_name='Descripción', null=True, blank=True)
    diagnostico_diferencial = models.CharField(max_length=4000, verbose_name='Descripción', null=True, blank=True)
    diagnostico_presuntivo = models.CharField(max_length=4000, verbose_name='Descripción', null=True, blank=True)
    examenes_laboratorio = models.CharField(max_length=4000, verbose_name='Descripción', null=True, blank=True)
    imagenes_diagnosticas = models.CharField(max_length=4000, verbose_name='Descripción', null=True, blank=True)
    diagnostico_definitivo = models.CharField(max_length=4000, verbose_name='Descripción', null=True, blank=True)
    observaciones_tratamiento = models.CharField(max_length=4000, verbose_name='Descripción', null=True, blank=True)
    pronostico = models.CharField(max_length=4000, verbose_name='Descripción', null=True, blank=True)
    notas = models.CharField(max_length=4000, verbose_name='Descripción', null=True, blank=True)
    motivo_cita = models.ForeignKey('MotivoCita', on_delete=models.CASCADE,null = True)
    descripcion_inyectologia = models.CharField(max_length=4000, verbose_name='Descripción',null=True, blank=True)
    sistema_linfatico = models.CharField(max_length=4000, verbose_name='Sistema linfatico', null=True, blank=True)
    sistema_tegumentario = models.CharField(max_length=4000, verbose_name='Sistema tegumentario', null=True, blank=True)
    sistema_cardiovascular = models.CharField(max_length=4000, verbose_name='Sistema cardiovascular', null=True, blank=True)
    sistema_respiratorio = models.CharField(max_length=4000, verbose_name='Sistema respiratorio', null=True, blank=True)
    sistema_digestivo = models.CharField(max_length=4000, verbose_name='Sistema digestivo', null=True, blank=True)
    sistema_musculoesqueletico = models.CharField(max_length=4000, verbose_name='Sistema musculoesqueletico', null=True, blank=True)
    sistema_nervioso = models.CharField(max_length=4000, verbose_name='Sistema nervioso', null=True, blank=True)
    sistema_urinario = models.CharField(max_length=4000, verbose_name='Sistema urinario', null=True, blank=True)
    sistema_reproductivo = models.CharField(max_length=4000, verbose_name='Sistema reproductivo', null=True, blank=True)
    descripcion_procedimiento = models.CharField(max_length=4000, verbose_name='Descripcion procedimiento', null=True, blank=True)

    def nombre_archivo(self):
        if len(str(self.archivo_zip).split('/')) == 2:
            return str(self.archivo_zip).split('/')[1]
        elif len(str(self.archivo_zip).split('/')) == 1:
            return str(self.archivo_zip).split('/')[0]
        else:
            return str(self.archivo_zip)


class Documento(models.Model):
    file = models.FileField(upload_to=get_upload_to_documento, verbose_name='Archivo')
    fecha_carga = models.DateTimeField(auto_now_add=True)
    historia = models.ForeignKey(HistoriaClinica, on_delete=models.CASCADE, null=True, blank=True)
    area_historia = models.CharField(max_length=500, verbose_name='Area', default='Motivo consulta')

    def save(self, *args, **kwargs):
        #print("Save documento!!!!")
        if self.file.url.endswith('.jpg') or self.file.url.endswith('.JPG') or self.file.url.endswith('.JPEG') or self.file.url.endswith('.jpeg'):
            #print(str(self.file) +": "+ str(self.file.size))
            if self.file.size > 1000000:
                self.file = self.compressImage(self.file)
        super(Documento, self).save(*args, **kwargs)

    def compressImage(self, uploadedImage):
        try:
            imageTemproary = Image.open(uploadedImage)
            outputIoStream = BytesIO()
            imageTemproaryResized = imageTemproary.resize((1020, 573))
            imageTemproary.save(outputIoStream, format='JPEG', quality=60)
            outputIoStream.seek(0)
            uploadedImage = InMemoryUploadedFile(outputIoStream, 'ImageField', "%s.jpg" % uploadedImage.name.split('.')[0], 'image/jpeg', sys.getsizeof(outputIoStream), None)
        except:
            print("imagen no encontrada")
        return uploadedImage

    def nombre(self):
        if len(str(self.file.name).split('/')) == 4:
            return str(self.file.name).split('/')[3]
        elif len(str(self.file.name).split('/')) == 3:
            return str(self.file.name).split('/')[2]
        elif len(str(self.file.name).split('/')) == 2:
            return str(self.file.name).split('/')[1]
        elif len(str(self.file.name).split('/')) == 1:
            return str(self.file.name).split('/')[0]
        else:
            return str(self.file.name)

    def __str__(self):
        if len(str(self.file).split('/')) == 2:
            return str(self.file).split('/')[1]
        elif len(str(self.file).split('/')) == 1:
            return str(self.file).split('/')[0]
        else:
            return str(self.file)

class MotivoArea(models.Model):
    area_consulta =  models.ForeignKey(Tratamiento, on_delete=models.CASCADE)
    historia_clinica = models.ForeignKey(HistoriaClinica, on_delete=models.CASCADE)
    estado = models.CharField(max_length=10, verbose_name="Estado", choices=ESTADOS_HISTORIA, default='Activa')

citas/templates/agregar_documento_historia.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

<!--form class="form-horizontal" method="POST" enctype="multipart/form-data" action="" autocomplete="off">{% csrf_token %}
    {% bootstrap_field form.file label_class="control-label col-lg-3" field_class="col-lg-9" %}
    {% bootstrap_button "Agregar" button_type="submit" button_class="btn btn-primary m-r-20" %}
</form-->

{% block content %}
<!--div class="modal-dialog modal-sm">
    <div class="modal-content animated fadeIn">
        <form class="form-horizontal" method="POST" enctype="multipart/form-data" action="" autocomplete="off">{% csrf_token %}
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">Agregar archivo</h4>
            </div>
            <div class="modal-body" style="height: 100px;">
                {% bootstrap_field form.file label_class="control-label col-lg-3" field_class="col-lg-9" %}

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal">Cancelar</button>
                {% bootstrap_button "Agregar" button_type="submit" button_class="btn btn-primary m-r-20" %}
            </div>
        </form>
    </div>
</div-->
    <div class="row">
        <div class="col-sm-12">
            <h4 class="page-title">
                {% if modificar %}
                    Modificar archivo
                {% else %}
                    Agregar archivo
                {% endif %}
            </h4>
        </div>
    </div>
    <form class="form-horizontal" method="POST" enctype="multipart/form-data" action="" autocomplete="off">{% csrf_token %}
        <div class="card-box">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group" style="margin: 15px;">
                        {% bootstrap_field form.file label_class="control-label col-lg-3" field_class="col-lg-9" %}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group" style="margin: 15px;">
                    </div>
                </div>
            </div>
        </div>
        <div class="text-center submit-btns">
            {% if modificar %}
                {% bootstrap_button "Guardar cambios" button_type="submit" button_class="btn btn-primary m-r-20" %}
            {% else %}
                {% bootstrap_button "Agregar" button_type="submit" button_class="btn btn-primary m-r-20" %}
            {% endif %}
            <a href="#" onclick="window.history.back();" class="btn btn-danger">Cancelar</a>
        </div>
    </form>
{% endblock content %}

citas/templates/agregar_otra_historia.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block title %}
    Registrar Historia Clinica
{% endblock title %}

{% block extrahead %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/select2.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/css/bootstrap-select.min.css" />
{% endblock%}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <h4 class="page-title">
                {% if modificar %}
                    Modificar historia
                {% else %}
                    Agregar historia
                {% endif %}
            </h4>
        </div>
    </div>
    <form class="form-horizontal" method="POST" enctype="multipart/form-data" action="" autocomplete="off">{% csrf_token %}
        <div class="card-box">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group" style="margin: 15px;">
                        {% bootstrap_field form.tratamiento label_class="control-label col-lg-3" field_class="col-lg-9" %}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group" style="margin: 15px;">
                        {% bootstrap_field form.archivo_zip label_class="control-label col-lg-3" field_class="col-lg-9" %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group" style="margin: 15px;">
                        {% bootstrap_field form.descripcion label_class="control-label col-lg-3" field_class="col-lg-9" %}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group" style="margin: 15px;">
                        {% bootstrap_field form.fecha label_class="control-label col-lg-3" field_class="col-lg-9" %}
                    </div>
                    <div class="form-group" style="margin: 15px;">
                        {% bootstrap_field form.estado label_class="control-label col-lg-3" field_class="col-lg-9" %}
                    </div>
                </div>
            </div>
        </div>
        <div class="text-center submit-btns">
            {% if modificar %}
                {% bootstrap_button "Guardar cambios" button_type="submit" button_class="btn btn-primary m-r-20" %}
            {% else %}
                {% bootstrap_button "Agregar" button_type="submit" button_class="btn btn-primary m-r-20" %}
            {% endif %}
            <a href="#" onclick="window.history.back();" class="btn btn-danger">Cancelar</a>
        </div>
    </form>
{% endblock content %}

{% block plugins %}
    <script type="text/javascript" src="{% static 'js/select2.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/moment.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/js/bootstrap-select.min.js"></script>

    <script type="text/javascript">
        $(function () {
            $('.datetime-input').datetimepicker({
                format:'DD/MM/YYYY HH:mm'
            });
        });
    </script>
{% endblock %}

citas/templates/registrar_cita.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block title %}
Registrar Cita
{% endblock title %}

{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{% static 'css/select2.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">

    <style>
        .select2-selection__rendered {
            line-height: 31px !important;
        }
        .select2-container .select2-selection--single {
            height: 35px !important;
        }
        .select2-selection__arrow {
            height: 34px !important;
        }
    </style>
{% endblock%}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title">
            {% if modificar %}
            Modificar cita
            {% else %}
            Agregar cita
            {% endif %}
        </h4>
        <ol class="breadcrumb">
            <li><a href="/usuario/index/">Inicio</a></li>
            <li><a href="/citas/listar_citas/">Agenda</a></li>
            <li class="active"><a>{% if modificar %}Modificar cita{% else %}Agregar cita{% endif %}</a></li>
        </ol>
    </div>
</div>
<form class="form-horizontal" method="POST" action="" autocomplete="off">{% csrf_token %}
    <div class="card-box">
        <div class="row">
            {% for field in form %}
            <div class="col-md-6">
                <div class="form-group" style="margin: 15px;">
                    {% bootstrap_field field label_class="control-label col-lg-3" field_class="col-lg-9" %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="text-center submit-btns">
        {% if modificar %}
            {% bootstrap_button "Guardar cambios" button_type="submit" button_class="btn btn-primary m-r-20" %}
        {% else %}
            {% bootstrap_button "Agregar" button_type="submit" button_class="btn btn-primary m-r-20 boton_agregar" %}
        {% endif %}
        <a href="#" onclick="window.history.back();" class="btn btn-danger">Cancelar</a>
    </div>
</form>
{% endblock content %}

{% block plugins %}
<script type="text/javascript" src="{% static 'js/select2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/moment.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>


<script type="text/javascript">



    //console.log('{{ fecha }}')
    $(function () {
        $('#firstdate').datetimepicker({
            format: 'DD/MM/YYYY HH:mm',
            date: new Date("{{ fecha }}")
        });
        $('#seconddate').datetimepicker({
            format: 'DD/MM/YYYY HH:mm'
        });

        $('#id_mascota').select2();
        $('#id_veterinario').select2();

        $('.boton_agregar').click(
            function () {
                if($('#id_mascota').val() == ''){
                    swal({
                        icon: 'error',
                        title: 'Debe seleccionar una mascota',
                        button: 'Ok'
                    });
                    setTimeout(function(){
                        $("#pageLoader").hide();
                        $('.button_save').removeAttr('disabled');
                    }, 500);
                    
                }
                if($('#id_veterinario').val() == ''){
                    swal({
                        icon: 'error',
                        title: 'Debe seleccionar un veterinario',
                        button: 'Ok'
                    });
                    setTimeout(function(){
                        $("#pageLoader").hide();
                        $('.button_save').removeAttr('disabled');
                    }, 500);
                    
                }
            }
        );
    });
</script>
{% endblock %}