caja/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    #path('registrar_cita/', CrearCita.as_view(), name="registrar_cita"),
    path('listar_pagos_hoy/', ListarPagosHoy.as_view(), name="listar_pagos_hoy"),
    path('abrir_caja/', abrir_caja, name="abrir_caja"),
    path('cerrar_caja/<int:id_caja>', cerrar_caja, name="cerrar_caja"),
    path('listar_cajas/', ListarCajas.as_view(), name="listar_cajas"),
    path('detalle_caja/<int:id_caja>/', ListarPagosSelected.as_view(), name="detalle_caja"),
    path('registrar_compra_caja/', registrar_compra_caja, name="registrar_compra_caja"),
    path('registrar_pago_caja/', crearPago_caja, name="registrar_pago_caja"),
    path('registrar_gasto_caja/', CrearGastoCaja.as_view(), name="registrar_gasto"),
    path('ajax/registrar_pago_caja/', registrarPago_caja, name="ajax_registrar_pago"),
    path('agregar_caja/', agregar_caja, name="agregar_caja"),
]

insumos/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('registrar_insumo/', CrearInsumo.as_view(), name="registrar_insumo"),
    path('editar_insumo/<int:pk>/', EditarInsumo.as_view(), name="editar_insumo"),
    path('detalle_insumo/<int:pk>/', DetalleInsumo.as_view(), name='detalle_insumo'),
    path('eliminar_insumo/', eliminar_insumo, name="eliminar_insumo"),
    path('inactivar_insumo/', inactivar_insumo, name="inactivar_insumo"),
    path('ajax/obtener_insumos/', obtener_insumos, name="obtener_insumos"),
]

insumos/models.py
from django.db import models
import sys
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
from citas.models import HistoriaClinica, Hospitalizacion
from desparasitacion.models import Desparasitacion
from vacunacion.models import Vacunacion
from bodegas.models import Bodega


ESTADOS = (('Activo','Activo'),('Inactivo','Inactivo'))
UNIDADES_MEDIDA = (('ml','Mililitros (ml)'),('l','Litros (l)'),('g','Gramos (g)'),('mg','Miligramos (mg)'),('kg','Kilogramos (kg)'), ('tabs', 'Tabletas (tabs)'))


def get_upload_to(instance, filename):
    return 'upload/insumos/%s/%s' % (instance.nombre, filename)


def validate_file_extension(value):
    import os
    from django.core.exceptions import ValidationError
    ext = os.path.splitext(value.name)[1]  # [0] returns path+filename
    valid_extensions = ['.jpg', '.JPG', '.jpeg', '.JPEG', '.png', '.PNG']
    if not ext.lower() in valid_extensions:
        raise ValidationError(u'La extensión del archivo no es valida.')


class Insumo(models.Model):
    nombre = models.CharField(max_length=100, verbose_name='Nombre')
    codigo = models.CharField(max_length=50, verbose_name='Número de lote', blank=True, null=True)
    codigo_inventario = models.CharField(max_length=50, verbose_name='Código de barras', blank=True, null=True)
    descripcion = models.CharField(max_length=800, verbose_name='Descripción', null=True, blank=True)
    estado = models.CharField(max_length=20, verbose_name="Estado", choices=ESTADOS, default='Activo')
    cantidad = models.DecimalField(max_digits=9, decimal_places=1, verbose_name='Cantidad', default=0)
    fecha_vencimiento = models.DateField(null=True, blank=True)
    unidad_medida = models.CharField(max_length=100, verbose_name='Unidad de medida', choices=UNIDADES_MEDIDA, default='ml')
    cantidad_unidad = models.DecimalField(max_digits=9, decimal_places=1, verbose_name='Cantidad por unidad', default=0)
    foto = models.ImageField(upload_to=get_upload_to, validators=[validate_file_extension], null=True, blank=True)
    cantidad_por_unidad = models.BooleanField(default=False)
    cantidad_total_unidades = models.DecimalField(max_digits=9, decimal_places=1, verbose_name='Cantidad total unidades', default=0)
    stock_minimo = models.PositiveIntegerField(verbose_name='Stock minimo', default=1)
    bodega = models.ForeignKey(Bodega, on_delete=models.CASCADE, default=1)
    precio_compra = models.DecimalField(max_digits=50, decimal_places=0, default=0)

    def save(self, *args, **kwargs):
        if self.cantidad_total_unidades == 0:
            self.cantidad_total_unidades = float(self.cantidad) * float(self.cantidad_unidad)
        if self.foto:
            if self.foto.url.endswith('.png'):
                print("Es un png")
                self.foto = self.foto
            else:
                self.foto = self.compressImage(self.foto)
        super(Insumo, self).save(*args, **kwargs)

    def compressImage(self, uploadedImage):
        try:
            imageTemproary = Image.open(uploadedImage)
            outputIoStream = BytesIO()
            imageTemproaryResized = imageTemproary.resize((1020, 573))
            imageTemproary.save(outputIoStream, format='JPEG', quality=60)
            outputIoStream.seek(0)
            uploadedImage = InMemoryUploadedFile(outputIoStream, 'ImageField', "%s.jpg" % uploadedImage.name.split('.')[0],
                                                 'image/jpeg', sys.getsizeof(outputIoStream), None)
        except:
            print("imagen no encontrada")
        return uploadedImage

    def __str__(self):
        if self.codigo:
            return self.nombre + " - " + self.codigo
        else:
            return self.nombre


class InsumoHistoria(models.Model):
    historia = models.ForeignKey(HistoriaClinica, on_delete=models.CASCADE)
    insumo = models.ForeignKey(Insumo, on_delete=models.CASCADE)
    cantidad_requerida = models.DecimalField(max_digits=9, decimal_places=1, verbose_name='Cantidad', default=0)
    unidad_medida = models.CharField(max_length=200, verbose_name='Unidad de medida')
    tipo_unidad_medida = models.CharField(max_length=200, verbose_name='Tipo de unidad')


class InsumoDesparasitacion(models.Model):
    desparasitacion = models.ForeignKey(Desparasitacion, on_delete=models.CASCADE)
    insumo = models.ForeignKey(Insumo, on_delete=models.CASCADE)
    cantidad_requerida = models.DecimalField(max_digits=9, decimal_places=1, verbose_name='Cantidad', default=0)
    unidad_medida = models.CharField(max_length=200, verbose_name='Unidad de medida')
    tipo_unidad_medida = models.CharField(max_length=200, verbose_name='Tipo de unidad')


class InsumoVacunacion(models.Model):
    vacunacion = models.ForeignKey(Vacunacion, on_delete=models.CASCADE)
    insumo = models.ForeignKey(Insumo, on_delete=models.CASCADE)
    cantidad_requerida = models.DecimalField(max_digits=9, decimal_places=1, verbose_name='Cantidad', default=0)
    unidad_medida = models.CharField(max_length=200, verbose_name='Unidad de medida')
    tipo_unidad_medida = models.CharField(max_length=200, verbose_name='Tipo de unidad')


class InsumoHospitalizacion(models.Model):
    hospitalizacion = models.ForeignKey(Hospitalizacion, on_delete=models.CASCADE)
    insumo = models.ForeignKey(Insumo, on_delete=models.CASCADE)
    cantidad_requerida = models.DecimalField(max_digits=9, decimal_places=1, verbose_name='Cantidad', default=0)
    unidad_medida = models.CharField(max_length=200, verbose_name='Unidad de medida')
    tipo_unidad_medida = models.CharField(max_length=200, verbose_name='Tipo de unidad')

insumos/views.py
from django.shortcuts import render
from django.views.generic import *
from .forms import *
from .models import *
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from productos.models import HistorialInventario
import math
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.contrib import messages
from gastos.models import GastoInsumo
from usuarios.models import Usuario
from django.db.models import Q
from itertools import chain
from django.db.models import Count
from django.core import serializers


class CrearInsumo(SuccessMessageMixin, CreateView):
    model = Insumo
    form_class = CrearInsumoForm
    template_name = "registrar_insumo.html"
    success_url = reverse_lazy('listar_productos')
    success_message = "Insumo agregado con exito!"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(CrearInsumo, self).dispatch(request, *args, **kwargs)

    def form_valid(self,form):
        insumo = form.instance

        responsable = get_object_or_404(Usuario, id=self.request.user.id)

        historia_transaccion = HistorialInventario(nombre_transaccion='Registro',tipo_elemento='Insumo',responsable=responsable)
        historia_transaccion.save()

        insumo.save()
        historia_transaccion.id_elemento = insumo.id
        historia_transaccion.save()

        return super(CrearInsumo, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CrearInsumo, self).get_context_data(**kwargs)
        context['modificar'] = False
        context['menu_inventario'] = True
        return context


class EditarInsumo(SuccessMessageMixin, UpdateView):
    model = Insumo
    form_class = CrearInsumoForm
    template_name = "registrar_insumo.html"
    success_url = reverse_lazy('listar_productos')
    success_message = "¡El insumo fue modificado con exito!"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(EditarInsumo, self).dispatch(request, *args, **kwargs)

    def form_valid(self,form):
        insumo = form.instance

        mi_insumo = get_object_or_404(Insumo, id=insumo.id)

        if (mi_insumo.cantidad != insumo.cantidad) or (mi_insumo.cantidad_unidad != insumo.cantidad_unidad):
            cantidad_nueva = insumo.cantidad
            insumo.cantidad_total_unidades = cantidad_nueva * insumo.cantidad_unidad

        responsable = get_object_or_404(Usuario, id=self.request.user.id)

        historia_transaccion = HistorialInventario(nombre_transaccion='Modificación de información',tipo_elemento='Insumo', id_elemento=insumo.id,responsable=responsable)
        historia_transaccion.save()

        self.object = form.save()
        return super(EditarInsumo, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(EditarInsumo, self).get_context_data(**kwargs)
        context['modificar'] = True
        context['menu_inventario'] = True
        return context


class DetalleInsumo(DetailView):
    model = Insumo
    template_name = "detalle_elemento.html"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(DetalleInsumo, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(DetalleInsumo, self).get_context_data(**kwargs)
        context['menu_inventario'] = True
        context['tipo_elemento'] = 'insumo'

        historial_inventario = HistorialInventario.objects.filter(tipo_elemento='Insumo',
                                                                  id_elemento=self.kwargs['pk'],
                                                                  tipo_transaccion='Inventario')
        context['historial_inventario'] = historial_inventario

        historial_ventas = HistorialInventario.objects.filter(tipo_elemento='Insumo',
                                                              id_elemento=self.kwargs['pk'],
                                                              tipo_transaccion='Ventas')
        context['historial_ventas'] = historial_ventas

        historial_compras = HistorialInventario.objects.filter(tipo_elemento='Insumo',
                                                               id_elemento=self.kwargs['pk'],
                                                               tipo_transaccion='Compras')
        context['historial_compras'] = historial_compras

        compras = GastoInsumo.objects.filter(insumo_id=self.kwargs['pk'])

        context['compras'] = compras

        mi_elemento = Insumo.objects.get(id=self.kwargs['pk'])

        if mi_elemento.cantidad_unidad != 0 and mi_elemento.cantidad_por_unidad:
            unidades_enteras = math.floor(float(mi_elemento.cantidad_total_unidades) / int(mi_elemento.cantidad_unidad))
            cantidad_no_entera = round((float(mi_elemento.cantidad_total_unidades) % int(mi_elemento.cantidad_unidad)),1)
        else:
            unidades_enteras = mi_elemento.cantidad
            cantidad_no_entera = 0

        if cantidad_no_entera == 0:
            if mi_elemento.cantidad_por_unidad:
                context['disponibilidad'] = str(unidades_enteras) + " unidades de " + str(
                    mi_elemento.cantidad_unidad) + " " + mi_elemento.unidad_medida
            else:
                context['disponibilidad'] = str(unidades_enteras) + " unidades"
        else:
            context['disponibilidad'] = str(unidades_enteras) + " unidades de " + str(
                mi_elemento.cantidad_unidad) + " " + mi_elemento.unidad_medida + " y 1 unidad de " + str(
                cantidad_no_entera) + " " + mi_elemento.unidad_medida

        return context


def eliminar_insumo(request):
    id_insumo = request.GET.get('id', '')
    insumo = get_object_or_404(Insumo, pk=id_insumo)
    insumo.delete()
    messages.success(request, '¡Insumo eliminado con exito!')
    data = {
        'eliminacion': True
    }
    return JsonResponse(data)


def inactivar_insumo(request):
    id_insumo = request.GET.get('id', '')
    insumo = get_object_or_404(Insumo, pk=id_insumo)
    insumo.estado = 'Inactivo'
    insumo.save()
    messages.success(request, '¡Insumo eliminado con exito!')
    data = {
        'eliminacion': True
    }
    return JsonResponse(data)


def obtener_insumos(request):

    all_insumos = Insumo.objects.filter(estado='Activo',bodega=1).exclude(Q(cantidad=0) & Q(cantidad_por_unidad=False)).exclude(Q(cantidad_total_unidades=0) & Q(cantidad_por_unidad=True))

    elementos_por_codigo = chain(
        Insumo.objects.distinct('codigo_inventario').filter(estado='Activo',bodega=1).exclude(
            codigo_inventario__isnull=True),
        Insumo.objects.filter(codigo_inventario__isnull=True, estado='Activo',bodega=1))
    elementos_repetidos = []
    for element in list(
            Insumo.objects.filter(bodega=1).values('codigo_inventario').annotate(cantidad=Count('codigo_inventario'))):
        if element['cantidad'] > 1:
            elementos_repetidos.append(element['codigo_inventario'])
    data = {
        'all_insumos': serializers.serialize('json', all_insumos),
        'elementos_por_codigo': serializers.serialize('json', elementos_por_codigo),
        'codigos_elementos': elementos_repetidos
    }
    return JsonResponse(data)

insumos/templates/registrar_insumo.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block title %}
    Inventario
{% endblock title %}

{% block extrahead %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">
{% endblock%}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <h4 class="page-title">
                {% if modificar %}
                    Editar insumo
                {% else %}
                    Agregar insumo
                {% endif %}
            </h4>
            <ol class="breadcrumb">
                <li><a href="/usuario/index/">Inicio</a></li>
                <li><a href="/productos/listar_productos/">Inventario</a></li>
                <li class="active"><a>{% if modificar %}Editar insumo{% else %}Agregar insumo{% endif %}</a></li>
            </ol>
        </div>
    </div>
    <form class="form-horizontal" method="POST" action="" autocomplete="off" enctype="multipart/form-data">{% csrf_token %}
        <div class="card-box" style="padding-left: 15px;">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group" style="margin: 15px;">
                        {% bootstrap_field form.nombre label_class="control-label col-lg-3" field_class="col-lg-9" %}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group" style="margin: 15px;">
                        {% bootstrap_field form.codigo_inventario label_class="control-label col-lg-3" field_class="col-lg-9" %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group" style="margin: 15px;">
                        {% bootstrap_field form.codigo label_class="control-label col-lg-3" field_class="col-lg-9" %}
                    </div>
                    <div class="form-group" style="margin: 15px;">
                        {% bootstrap_field form.stock_minimo label_class="control-label col-lg-3" field_class="col-lg-9" %}
                    </div>
                    <div class="form-group" style="margin: 15px;">
                        {% bootstrap_field form.bodega label_class="control-label col-lg-3" field_class="col-lg-9" %}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group" style="margin: 15px;">
                        {% bootstrap_field form.descripcion label_class="control-label col-lg-3" field_class="col-lg-9" %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group" style="margin: 15px;">
                        {% bootstrap_field form.cantidad label_class="control-label col-lg-3" field_class="col-lg-9" %}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group" style="margin: 15px;">
                        {% bootstrap_field form.fecha_vencimiento label_class="control-label col-lg-3" field_class="col-lg-9" %}
                    </div>
                </div>
            </div>
            <div class="row">
                 <div class="col-md-6">
                     <div class="form-group" style="margin: 15px;">
                        {% bootstrap_field form.precio_compra label_class="control-label col-lg-3" field_class="col-lg-9" %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group" style="margin: 15px;">
                        {% bootstrap_field form.foto label_class="control-label col-lg-3" field_class="col-lg-9" %}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group" style="margin: 15px;">
                        {% bootstrap_field form.cantidad_por_unidad label_class="control-label col-lg-3" field_class="col-lg-9" %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div id="contenedor_unidad_medida">
                        <div class="form-group" style="margin: 15px;">
                            {% bootstrap_field form.unidad_medida label_class="control-label col-lg-3" field_class="col-lg-9" %}
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div id="contenedor_cantidad_unidad">
                        <div class="form-group" style="margin: 15px;">
                            {% bootstrap_field form.cantidad_unidad label_class="control-label col-lg-3" field_class="col-lg-9" %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="text-center submit-btns">
            {% if modificar %}
                {% bootstrap_button "Guardar cambios" button_type="submit" button_class="btn btn-primary m-r-20" %}
            {% else %}
                {% bootstrap_button "Agregar" button_type="submit" button_class="btn btn-primary m-r-20" %}
            {% endif %}
            <a href="{% url 'listar_productos' %}" class="btn btn-danger">Cancelar</a>
        </div>
    </form>
{% endblock content %}

{% block plugins %}
<script>

    $(document).ready(function(){

        $('.fecha-vencimiento').datetimepicker({
            format: 'DD/MM/YYYY',
            locale: 'es'
        });

        if($('#id_cantidad_por_unidad').is(":checked")){

        }else {
            $('#contenedor_unidad_medida').hide();
            $('#contenedor_cantidad_unidad').hide();
        }
    });

    $('#id_cantidad_por_unidad').click(function () {
        if ($('#id_cantidad_por_unidad').is(":checked"))
        {
            $('#contenedor_unidad_medida').show();
            $('#contenedor_cantidad_unidad').show();
        }else{
            $('#contenedor_unidad_medida').hide();
            $('#contenedor_cantidad_unidad').hide();
        }
    });
</script>
{% endblock %}